// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7f27d41f-c5e9-4c6d-9f24-60a6d2107521",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_FDp3QaOF5",
    "aws_user_pools_web_client_id": "9udn8vnr8gdbg0bdrt1ocnr5c",
    "oauth": {}
};


export default awsmobile;
